### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by Mesqualito** [pejonp/vbus#1]
Thanks for your good work! Please can you tell me how to change the password in your config again? I made a mistake while setting it once - and I lost it for the RESOL LAN-Adapter, so I resetted the LAN-Adapter and now I have to adjust the password in fhem.

Sincerely,
Jochen

**Comment by pejonp** [comment]
https://github.com/pejonp/vbus (at the bottom of the page)
or
https://github.com/pejonp/vbus/blob/master/set%20Passwd%20VBUS.JPG

**Comment by Mesqualito** [comment]
Sorry for my blindness and thanks a lot :-)

**Comment by pejonp** [comment]
@Mesqualito 
no problem ;-)
